# Generated by Django 4.1 on 2023-01-17 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marble", "0003_alter_resimler_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="resimler",
            options={"get_latest_by": "created_at"},
        ),
        migrations.AddField(
            model_name="resimler",
            name="average_color",
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resimler",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="resimler",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="resimler",
            name="image",
            field=models.ImageField(upload_to="media/"),
        ),
    ]
